In [1]:
from importlib import reload
from qt_app import app,eastmoney_parser,ratio_calculator,utils,kelly
utils = reload(utils)
kelly = reload(kelly)

config = utils.config
data_path = config['data_path']
pkg_path = utils.pkg_path

In [5]:
import requests

# replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
url = 'https://www.alphavantage.co/query?function=NEWS_SENTIMENT&tickers=AAPL&apikey=demo'
r = requests.get(url)
data = r.json()

print(data)

ModuleNotFoundError: No module named 'django_project'

ModuleNotFoundError: No module named 'django_project'

In [3]:
kc = kelly.KellyCriterion()

price_df=kc.loadClosePrice(max_lookback_years=0.13)
price_df

csv_filepath:  ../data/short_term_solvency_ratio\tblStockPickedWithSolvencyR2023-08-23.csv
Downloading adjusted daily close data from Yahoo! Finance...
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

            603096.SS  600276.SS  688078.SS  601398.SS  000848.SZ
Date
2023-07-14  20.500000  47.520000  50.000000     4.5665       8.80
2023-07-17  20.389999  47.200001  50.349998     4.5700       8.73
2023-07-18  20.070000  47.200001  49.570000     4.5400       8.72
2023-07-19  20.530001  46.689999  50.009998     4.5600       8.73
2023-07-20  20.129999  45.959999  48.849998     4.5800       8.74
2023-07-21  20.129999  45.930000  47.750000     4.5800       8.91
2023-07-24  20.250000  47.290001  48.650002     4.5700       8.91
2023-07-25  20.450001  47.759998  48.770000     4.6200       8.96
2023-07-26  20.260000  48.080002  47.480000     4.6300       9.01
2023-07-27  19.830000  48.110001  46.270000     4.7000       8.99
2023-07-28  19.530001  49.049999  47.980000     4.7900       9.15
2023-07-31  19.860001  44.580002  45.860001     4.7700       9.20
2023-08-01  19.790001  43.380001  45.889999     4.7800       9.09
2023-08-02  19.540001  42.279999  46.779999     4.6700       9.07
2023-08-03  19.299999  42.270000  46.099998     4.7200       9.24
2023-08-04  19.639999  41.070000  47.189999     4.7400       9.12
2023-08-07  19.750000  39.130001  47.340000     4.7100       9.06
2023-08-08  20.389999  40.139999  46.419998     4.6800       9.16
2023-08-09  19.139999  40.209999  46.040001     4.7100       9.07
2023-08-10  19.430000  39.900002  46.230000     4.6900       9.04
2023-08-11  19.580000  39.200001  45.570000     4.6100       8.90
2023-08-14  19.629999  40.619999  46.619999     4.5600       8.87
2023-08-15  18.879999  40.500000  45.180000     4.6400       8.83
2023-08-16  18.580000  41.009998  43.680000     4.6400       8.84
2023-08-17  18.730000  40.570000  43.430000     4.6000       8.95
2023-08-18  18.520000  39.950001  43.029999     4.6100       8.76
2023-08-21  18.680000  38.799999  43.259998     4.5600       8.75
2023-08-22  19.139999  39.150002  45.080002     4.6200       8.53
2023-08-23  18.920000  38.700001  43.570000     4.6400       8.53
2023-08-24  19.299999  40.439999  43.349998     4.5900       8.59
2023-08-25  18.799999  40.720001  42.090000     4.6600       8.43
2023-08-28  19.010000  41.919998  41.000000     4.7300       8.43